deploy_composer_tags:
  only:
    - tags
  stage: test
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
deploy_composer_branches:
  only:
    - branches
  stage: test
  script:
    - curl -sS --show-error --fail --data branch=${CI_COMMIT_BRANCH} "https://__token__:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
